### ISSUE TITLE
Make indicator more accessiblity-friendly

### ISSUE THREAD

**Issue by CraigFoote** [CraigFoote/ca.footeware.gnomeshell.serverstatus#13]
Should not use color as the sole indicator of state. -GNOME HIG.

**Comment by CraigFoote** [comment]
Now using emojis and icons can be swapped out to customize.

**Comment by dhwalker** [comment]
I agree that color should not be the **sole** indicator of server state, but it would be nice to have it as **an** indicator. Would it be possible to make the server-up indicator be green, and the server-bad indicator be yellowish/orangeish?

Thanks for this extension, by the way. It's comforting to be able to see if my home server is up, even when I'm traveling.

**Comment by sacerdot** [comment]
I also agree that keeping the traditional traffic-light color scheme would have been much better. Server-up should be greenish and server-bad reddish/yellowish by default.

**Comment by CraigFoote** [comment]
I worried about that. I liked the traffic-light scheme but all the emojis I've seen have red angry and green puke colors so I went for that. I'd really like to get to a user-selectable set of icons but I'm not there yet. I think you can programmatically color svgs too. Anyway, I agree so I'll make the change. Thanks for the interest!

**Comment by CraigFoote** [comment]
Complete

**Comment by dhwalker** [comment]
Thanks!
