### ISSUE TITLE
Setting to change icon and color

### ISSUE THREAD

**Issue by insign** [CraigFoote/ca.footeware.gnomeshell.serverstatus#2]
Currently the icon and colors don't follows gnome guidelines.
But to be honest it is ugly to me.
So, let us customize?

**Comment by CraigFoote** [comment]
I assume the ugly colors you speak of are from the Dracula theme I had installed. This extension with Gnome 45 will use libadwaita and so now colors properly for light and dark themes. If you mean customize the colors used for Up, Down and Bad statuses, that would be a complete rewrite.

**Comment by CraigFoote** [comment]
Recent development conforms with light/dark themes.

**Comment by CraigFoote** [comment]
@insign, you can replace the four server* svg files in the assets folder to change indicator icon and color (I think).
