### ISSUE TITLE
Rename indicator

### ISSUE THREAD

**Issue by jonocodes** [CraigFoote/ca.footeware.gnomeshell.serverstatus#7]
Very cool extension.

It would be nice if you could name the server. 
So instead of seeing "https://www.gnome.org/" I could just have it say something like "Gnome" or whatever I want to call it. This is particulary useful for watching things on localhost and in my network since they may just be the same host with varying port numbers.

Also it would be nice to be able to reorder the list.

**Comment by CraigFoote** [comment]
RE: name - Great idea! I'll work on this but it will mean having to migrate gsettings to add the name to the schema.

RE: reorder list - yes I've thought of this. Drag and drop groups would be nice, arrow buttons otherwise I guess. I'll work on this too.

**Comment by jonocodes** [comment]
Thanks!
Also, if you click on a name in the indicator popup it would be nice to either visit that site in browser, or fire off a recheck immediately.

**Comment by CraigFoote** [comment]
You're just a font of good ideas. I like opening a browser to the URL.

**Comment by CraigFoote** [comment]
v19 for Gnome 45 has Name field now.

**Comment by jonocodes** [comment]
Wow. Fastest turnaround ever!

Once it hits gnome.extensions.org, I will give it a test.

**Comment by jonocodes** [comment]
Works well. Thanks

**Comment by CraigFoote** [comment]
Thanks. Needs a little polish still. Working on tucking each server's inputs under an expander now. Then moving via buttons in each expander. Got a lead on opening an URL in browser too. Loads of fun :)

**Comment by CraigFoote** [comment]
Just released re-ordering of servers in preferences and opening URL by clicking panel entry.

**Comment by jonocodes** [comment]
It works!

**Comment by CraigFoote** [comment]
Thanks for the ideas and the testing.
